### ISSUE TITLE
Error in Xcode 8: Nullability specifier '_Nullable' cannot be applied to non-pointer type 'NSError'

### ISSUE THREAD

**Issue by teddy-paytollo** [Automatic/Automatic-iOS-SDK#13]
I just installed the iOS AutomaticSDK via Cocoapod: pod "AutomaticSDK", "0.0.1"

And Xcode 8.2.1 is reporting the following error: 

Nullability specifier '_Nullable' cannot be applied to non-pointer type 'NSError'; did you mean to apply the specifier to the pointer?

<img width="1083" alt="screen shot 2017-03-06 at 11 52 03 am" src="https://cloud.githubusercontent.com/assets/22946501/23627346/450d1b88-0265-11e7-90fd-8dbb33923179.png">

which comes from the SDK header file.

**Comment by erichoracek** [comment]
Fixed in #14
