### ISSUE TITLE
Authorize App redirects to localhost

### ISSUE THREAD

**Issue by teddy-pt** [Automatic/Automatic-iOS-SDK#17]
Hey guys,

I made a call to the **authorizeWithScopes:success:failure:** api to connect with Automatic:
 
`authorizeWithScopes:(AUTClientScopes)scopes success:(void(^)(void))success failure:`

The call opens Safari and redirect me to _accounts.automatic.com/oauth/authorize/<client id, scope, ...>_  ...  then i entered my test Automatic account's username and password; and hit "Authorize App" button. The issue is it redirected me to localhost.

Hope this will be fixed soon. It's a blocker. Thanks!

**Comment by tguidon** [comment]
@teddy-paytollo check your "OAuth Redirect URL" on https://developer.automatic.com/ for the specific app. Is it set to localhost?

**Comment by teddy-paytollo** [comment]
@tguidon, thank you for pointing that out. Yes, the "oath redirect url" was localhost. I changed that url to my custom redirect url and now Safari opens my app. So that's part is fine. But now the success block of authorizeWithScope is not being called upon successful authorization.

**Comment by tguidon** [comment]
@teddy-pt not sure what could be wrong, I did not build the SDK just implementing. Here is how I have it working in Swift 3, hope it helps!

```Swift
    func checkOrGetAutomaticCredentials() {
        // Check if we have already auth'd and have a credential
        if let credential = AFOAuthCredential.retrieveCredential(withIdentifier: "credential") {
            // we have previous creds so lets store them in the client
            client.credential = credential
        } else {
            // lets get those creds
            client.authorize(with: [AUTClientScopes.trip, AUTClientScopes.location, AUTClientScopes.behavior], success: {
                guard let cred = self.client.credential else {
                    print("Credentials not there.")
                    return
                }
                // save so we do not need to log back in
                AFOAuthCredential.store(cred, withIdentifier: "credential")
            }) { (error) in
                print("Failed to authorize with error: \(error)")
            }
        }
    }
```

**Comment by teddy-pt** [comment]
thanks @tguidon. 
Actually the issue was that i didn't have my redirect url in the correct format. The correct format is  automatic-abc123://oauth, where abc123 is my app client id.

**Comment by teddy-pt** [comment]
thanks @tguidon.
Actually the issue was that i didn't have my redirect url in the correct format. The correct format is automatic-abc123://oauth, where abc123 is my app client id.
